name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Compile code
      run: |
        find src -name "*.java"
        javac -d out src/main/java/**/*.java src/main/java/Main.java
        
    - name: Run tests
      run: |
        echo "✅ Компиляция успешна!"
        echo "Проект собран корректно"