name: SonarCloud Analysis - Lab 3
on:
  push:
    branches: [ main ]

jobs:
  analyze:
    name: Analyze Lab 3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=LoliIRL_java-lab-3
            -Dsonar.organization=loliirl