name: SonarCloud Analysis
on:
  push:
    branches: [ main ]

jobs:
  analyze:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SonarScanner via Docker
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          docker run \
            --rm \
            -e SONAR_TOKEN="$SONAR_TOKEN" \
            -v "$(pwd):/usr/src" \
            sonarsource/sonar-scanner-cli:latest \
            -Dsonar.projectKey=LoliIRL_java-lab-3 \
            -Dsonar.organization=loliirl \
            -Dsonar.sources=src/main/java \
            -Dsonar.host.url=https://sonarcloud.io